src/objects/Addition__c.object
<CustomObject>
    <fields>
        <fullName>Number1_2__c</fullName>
        <label>Number3</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number1__c</fullName>
        <label>Number1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number2_2__c</fullName>
        <label>Number4</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number2__c</fullName>
        <label>Number2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Addition</label>
    <nameField>
        <label>Addition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Additions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/v5.cls
public class v5 {

    public Integer num1{get;set;}
    public Integer num2{get;set;}
    public Integer num3{get;set;}
    public Integer num4{get;set;}
    Addition__c tr = new Addition__c();
    public v5()
    {
        tr.Number1__c = num1;
        tr.Number1_2__c = num2;
        tr.Number2__c = num3;
        tr.Number2_2__c = num4;
    }
    
    public void add()
    {
        tr.Number1__c = num1;
        tr.Number1_2__c = num2;
        tr.Number2__c = num3;
        tr.Number2_2__c = num4;
        insert tr;
    }
}