src/objects/Candidate__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Employee_Type__c</fullName>
        <label>Employee Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Employee_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <displayFormat>EMPID-{0000}</displayFormat>
        <label>Candidate ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Employee_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>CEO</fullName>
    </customValue>
    <customValue>
        <fullName>CHAIRMAN</fullName>
    </customValue>
    <customValue>
        <fullName>DEVELOPER</fullName>
    </customValue>
    <customValue>
        <fullName>HR</fullName>
    </customValue>
    <customValue>
        <fullName>MANAGER</fullName>
    </customValue>
    <customValue>
        <fullName>TECHNICIAN</fullName>
    </customValue>
    <customValue>
        <fullName>TESTER</fullName>
    </customValue>
    <customValue>
        <fullName>INTERN</fullName>
    </customValue>
    <masterLabel>Employee Type</masterLabel>
</GlobalValueSet>

src/classes/login1.cls
public class login1 {
    
    public String email {get;set;}
    public String pass {get;set;}
    public List<Candidate__c> rec {set;get;}
    public login1(ApexPages.StandardController controller) {

    }
    public pagereference loging()
    {    
        
                    rec = [select Name,Email__c,Password__c,Employee_Type__c from Candidate__c where Email__c=:email];
                    
                    //if(rec[0].Password__c != pass)
                    //if(pass!='admin')
              /* if(rec[0].Employee_Type__c!='HR')
               {
                       pagereference pr = new pagereference('/apex/samplelogin');
                       return pr;
               }
               else
               {
                    if(rec[0].Password__c != pass)
                    {    
                        pagereference pr = new pagereference('/apex/login1');
                        return pr;
                        
                    }
                    else
                    {
                        pagereference pr = new pagereference('/apex/home1');
                        return pr;
                     }
                }*/
                    if(rec[0].Employee_Type__c!='CEO')
                    {
                        pagereference pr = new pagereference('/apex/login1');
                        return pr;
                    }
                    else
                    {
                        if(rec[0].Password__c != pass)
                        {    
                            pagereference pr = new pagereference('/apex/login1');
                            return pr;
                        }
                        else
                        {
                            pagereference pr = new pagereference('/apex/home1');
                            return pr;
                         }
                     }
    }
    public pagereference loging2()
    { 
        pagereference pr = new pagereference('/apex/login');
        return pr;
    }
}