src/objects/Candidate__c.object
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <displayFormat>EMPID-{0000}</displayFormat>
        <label>Candidate ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Weeksheet__c.object
<CustomObject>
    <fields>
        <fullName>Candidate__c</fullName>
        <label>Candidate</label>
        <referenceTo>Candidate__c</referenceTo>
        <relationshipLabel>Weeksheets</relationshipLabel>
        <relationshipName>Weeksheets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Weeksheet</label>
    <nameField>
        <displayFormat>WS-{0000}</displayFormat>
        <label>Weeksheet ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Weeksheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/dpage.cls
public class dpage
{
    Weeksheet__c tk = new Weeksheet__c() ;
    public String data { get; set; }
    public List<Weeksheet__c> list1 {get;set;}
    public List<Candidate__c> list2 {get;set;}
    public dpage() {
           
    }

   
    
    public dpage(ApexPages.StandardController controller) {
         this.tk = (Weeksheet__c)controller.getRecord();  
         try{ 
         data = apexpages.currentPage().getCookies().get('value').getValue(); 
         }catch(Exception e){}
         /*list1 = [select Candidate__c, Candidate__r.Name from Weeksheet__c where Candidate__r.Name=:data]; 
         tk.Candidate__c = list1[0].Candidate__c;*/
         list2 = [select Id from Candidate__c where Candidate__c.Name=:data];
         tk.Candidate__c = list2[0].Id;
    }

    
    
    public pagereference save()
    {
        
        
        insert tk;
        pagereference pr = new pagereference('/apex/wks');
        return pr;
    }
}