src/objects/Candidate__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Male</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Candidate</label>
    <nameField>
        <displayFormat>EMPID-{0000}</displayFormat>
        <label>Candidate ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/profile2.cls
public class profile2 {

    public profile2() {

    }

    
    public list<Candidate__c> wks {get;set;}
    Candidate__c cd = new Candidate__c();
    public String data;
    public profile2(ApexPages.StandardController controller) {
            data = apexpages.currentPage().getCookies().get('value').getValue();
            wks = [select Name,Email__c,Gender__c from Candidate__c where Name=:data];
            this.cd = (Candidate__c)controller.getRecord();
            
    }
    public boolean editSection {get;set;}
        
    public PageReference EdittheSection()
        {
        editSection = true;
        return null;
        }
       
        public PageReference save()
        {    
            update cd;
            pagereference pr = new pagereference('/apex/sampleprofile');
            return pr;
            
        }
}