src/objects/Candidate__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <displayFormat>EMPID-{0000}</displayFormat>
        <label>Candidate ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Weeksheet__c.object
<CustomObject>
    <fields>
        <fullName>Candidate__c</fullName>
        <label>Candidate</label>
        <referenceTo>Candidate__c</referenceTo>
        <relationshipLabel>Weeksheets</relationshipLabel>
        <relationshipName>Weeksheets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Weeksheet</label>
    <nameField>
        <displayFormat>WS-{0000}</displayFormat>
        <label>Weeksheet ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Weeksheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/expcheck.cls
public class expcheck {
    Weeksheet__c tk = new Weeksheet__c() ;
    public String data { get; set; }
    public String hold;
    public List<Weeksheet__c> list1 {get;set;}
    public expcheck(ApexPages.StandardController controller) {
      try{
        data = apexpages.currentPage().getCookies().get('value').getValue();
        }catch(Exception e){lout();}
        this.tk = (Weeksheet__c)controller.getRecord();
        list1 = [select Candidate__c, Candidate__r.Email__c from Weeksheet__c where Candidate__r.Name=:'akash.khan@simpsoftsolutuion.com'];
       try{tk.Candidate__c = list1[0].Candidate__c;}catch(Exception e){}
       
    }
    public pagereference save()
    {
        
        
        insert tk;
        pagereference pr = new pagereference('/apex/entryexpcheck');
        return pr;
    }
     public pagereference lout()
    {
        
        Cookie cook = new Cookie('value', hold, null, 0, false);
        pagereference pr = new pagereference('/apex/sampleentry');
        
        pr.setCookies(new Cookie[] {cook});
        
        return pr;
    }
     
}