src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Student</label>
    <nameField>
        <displayFormat>S-{00}</displayFormat>
        <label>Student ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/RowLockCheck.cls
public class RowLockCheck
{
	public static void executeB()
    {
        List<Student__c> std1 = [Select Name__c from Student__c where Name__c='Soumya'];
		//List<Student__c> std2 = [select Name__c from Student__c where Name__c='Soumya'];
        for(Student__c st :std1)
		{
			st.Name__c='Sneha';
			//st.Phone__c=123;
		}
        for(Student__c st :std1)
		{
			//st.Name__c='john';
			st.Phone__c=456;
		}
        update std1;
        update std1;
    }
}