src/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>comment__c</fullName>
        <label>comment</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <displayFormat>S-{00}</displayFormat>
        <label>Student ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/RetryTest.cls
public class RetryTest
{
    public static integer count=1;
    public static void modify()
    {
    	List<Student__c> stdnt = [Select Name__c,Phone__c,comment__c From Student__c Where Name__c='Soumya' FOR UPDATE];
		//System.debug(stdnt);
		for(Student__c st :stdnt)
		{
			st.Name__c='john';
			st.Phone__c=123;
            st.comment__c = 'comments for testing';
		}
		//System.debug(stdnt);
        try
        {
			update stdnt;
        }
        catch(DMLException e)
        {
            count=count+1;
            if(e.getMessage().contains('UNABLE_TO_LOCK_ROW'))//UNABLE_TO_LOCK_ROW  CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY
            {
                if(count<5)
                {
                    System.debug(count);
                	modify();
                }
                else
                {
                    System.debug(e);
                }
            }
            else
            {
                 System.debug(e);
            }
        }
    }
}