src/objects/Weeksheet__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Duration_hrs1__c</fullName>
        <label>Duration(hrs)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Duration_hrs2__c</fullName>
        <label>Duration(hrs)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Organization2__c</fullName>
        <label>Organization</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <label>Organization</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Particular2__c</fullName>
        <label>Particular</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Particular__c</fullName>
        <label>Particular</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Weeksheet</label>
    <nameField>
        <displayFormat>WS-{0000}</displayFormat>
        <label>Weeksheet ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Weeksheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/samepage.cls
public class samepage
{

    public samepage() {

    }

    public Weeksheet__c wk {get;set;}
    public Weeksheet__c setwk(Weeksheet__c op){
        this.wk=op;
        return wk;
    }
    public samepage(ApexPages.StandardController controller) {
            wk=new Weeksheet__c();
    }

    
    
    public pagereference save()
    {
        Weeksheet__c tk = new Weeksheet__c();
        tk.Date__c=wk.Date__c;
        tk.Duration_hrs1__c=wk.Duration_hrs1__c;
        tk.Duration_hrs2__c=wk.Duration_hrs2__c;
        tk.Organization__c=wk.Organization__c;
        tk.Organization2__c=wk.Organization2__c;
        tk.Particular__c=wk.Particular__c;
        tk.Particular2__c=wk.Particular2__c;
        insert tk;
        pagereference pr = new pagereference('https://c.ap8.visual.force.com/apex/wks');
        return pr;
    }
}