src/objects/Weeksheet__c.object
<CustomObject>
    <fields>
        <fullName>Duration_hrs1__c</fullName>
        <label>Duration(hrs)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Duration_hrs2__c</fullName>
        <label>Duration(hrs)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Organization2__c</fullName>
        <label>Organization</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <label>Organization</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Particular2__c</fullName>
        <label>Particular</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Particular__c</fullName>
        <label>Particular</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Weeksheet</label>
    <nameField>
        <displayFormat>WS-{0000}</displayFormat>
        <label>Weeksheet ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Weeksheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/sbpage.cls
public class sbpage {
    
    private ApexPages.StandardController stdCtrl {get; set;}
    Weeksheet__c tk = new Weeksheet__c();
    public List<Weeksheet__c> conts {set;get;}
    public string dt {set;get;}
    public sbpage(ApexPages.StandardController std)
    {
            stdCtrl=std;
            spage();
    }
    public void spage()
    {
        conts = [select Organization__c,Particular__c,Duration_hrs1__c,Organization2__c,Particular2__c,Duration_hrs2__c from Weeksheet__c where Organization__c=:'Simpsoft'];
    }
    
}